import {useState} from 'react';
import {Wallet,Plus} from 'lucide-react';
import {toast} from 'sonner';
import {departmentRequest} from '@/lib/local-auth';
import {type CaseSummary,type LedgerData,type LedgerRecord,type Currency,CURRENCIES,ENTRY_TYPES,newDepartmentRecord,moneyText,ledgerTotals} from '@/lib/departments';
import type {Permissions} from '@/lib/permissions';
import {todayISO,formatDate} from '@/lib/domain';
import {normalizeSearch} from '@/lib/case-browse';
import {Field,DateField,Empty} from '../shared';
import {OfficeSelect} from '../office-shared';
import PageNavigation from '../page-navigation';
import {CasePicker,DepartmentHistory,EditorDialog,StatusMessage,useRecords,exportCsv} from './shared';
export default function Accounting({cases,access}:{cases:CaseSummary[];access:Permissions}) {
 const {rows,loading,error,reload}=useRecords<LedgerData>('accounting');
 const [search,setSearch]=useState(''),[currency,setCurrency]=useState<Currency>('KWD'),[type,setType]=useState(''),[status,setStatus]=useState('posted'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[caseId,setCaseId]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<LedgerRecord|null>(null);
 const filtered=rows.filter(r=>r.payload.currency===currency&&(!type||r.payload.type===type)&&(!status||r.payload.status===status)&&(!caseId||r.caseId===caseId)&&(!from||r.payload.date>=from)&&(!to||r.payload.date<=to)&&normalizeSearch([r.payload.reference,r.payload.party,r.payload.notes,cases.find(c=>c.id===r.caseId)?.code].join(' ')).includes(normalizeSearch(search))).sort((a,b)=>b.payload.date.localeCompare(a.payload.date)||b.createdAt.localeCompare(a.createdAt));
 const totals=ledgerTotals(filtered,currency),pages=Math.max(1,Math.ceil(filtered.length/20)),current=Math.min(page,pages);
 const add=()=>setEditing(newDepartmentRecord('accounting','entry',{type:'fee',date:todayISO(),currency,amount:'',amountMinor:'0',reference:'',party:'',notes:'',status:'posted',voidReason:''}));
 return <><section className="department-hero"><div><div className="eyebrow">السجل المالي</div><h1>المحاسبة</h1><p>سجّل الأتعاب والمقبوضات والمصروفات مع مرجع كل حركة.</p></div><Wallet size={64}/></section>
 <div className="ledger-summary"><div className="ledger-balance"><span>الأتعاب المتبقية ضمن التصفية</span><b dir="ltr">{moneyText(totals.outstanding,currency)}</b><small>الأتعاب − المقبوضات</small></div><div className="ledger-totals">{(['fee','receipt','expense','net'] as const).map(k=><div key={k}><span>{k==='net'?'صافي المقبوضات بعد المصروفات':ENTRY_TYPES[k]}</span><b dir="ltr">{moneyText(totals[k],currency)}</b></div>)}</div></div>
 <section className="panel"><div className="department-toolbar"><h2>دفتر الحركات</h2><div className="actions">{access.canExport&&<button className="btn" onClick={()=>void exportCsv('accounting','Mawatheeq-ledger',[['التاريخ','النوع','المرجع','الطرف','القضية','المبلغ','العملة','الحالة','سبب الإلغاء'],...filtered.map(r=>[r.payload.date,ENTRY_TYPES[r.payload.type],r.payload.reference,r.payload.party,cases.find(c=>c.id===r.caseId)?.code||r.caseId,moneyText(r.payload.amountMinor,r.payload.currency),r.payload.currency,r.payload.status==='void'?'ملغى':'مرحّل',r.payload.voidReason])]).catch(e=>toast.error(e.message))}>تصدير الحركات</button>}{access.canEdit&&<button className="btn primary" onClick={add}><Plus size={17}/> قيد جديد</button>}</div></div>
 <div className="department-filters"><Field label="بحث الحركات" value={search} onChange={v=>{setSearch(v);setPage(1)}}/><OfficeSelect label="العملة" value={currency} onChange={v=>{setCurrency(v as Currency);setPage(1)}} options={Object.keys(CURRENCIES).map(k=>[k,k])}/><OfficeSelect label="نوع الحركة" value={type} onChange={v=>{setType(v);setPage(1)}} options={Object.entries(ENTRY_TYPES)} empty="جميع الأنواع"/><OfficeSelect label="حالة القيد" value={status} onChange={v=>{setStatus(v);setPage(1)}} options={[['posted','القيود المرحلة'],['void','القيود الملغاة']]} empty="جميع الحالات"/><DateField label="من تاريخ" value={from} onChange={v=>{setFrom(v);setPage(1)}}/><DateField label="إلى تاريخ" value={to} onChange={v=>{setTo(v);setPage(1)}}/><OfficeSelect label="تصفية بالقضية" value={caseId} onChange={v=>{setCaseId(v);setPage(1)}} options={cases.map(c=>[c.id,c.code||c.autoNumber||c.id])} empty="جميع القضايا"/></div>
 <p className="subtitle">الأرصدة حسب العملة وعوامل التصفية أعلاه. القيود الملغاة محفوظة ولا تدخل الأرصدة.</p>{from&&to&&from>to&&<p role="alert">تاريخ البداية بعد تاريخ النهاية.</p>}<StatusMessage loading={loading} error={error}/>{!loading&&!error&&<><div className="table-wrap"><table className="office-table ledger-table"><thead><tr><th>التاريخ / المرجع</th><th>الحركة</th><th>الطرف</th><th>القضية</th><th>المبلغ</th><th>الحالة</th><th>التفاصيل</th></tr></thead><tbody>{filtered.slice((current-1)*20,current*20).map(r=><tr key={r.id} className={r.payload.status==='void'?'ledger-void':''}><td>{formatDate(r.payload.date)}<small>{r.payload.reference}</small></td><td>{ENTRY_TYPES[r.payload.type]}</td><td>{r.payload.party}</td><td>{cases.find(c=>c.id===r.caseId)?.code||'مكتبي'}</td><td className="ledger-value" dir="ltr">{moneyText(r.payload.amountMinor,r.payload.currency)}</td><td>{r.payload.status==='void'?'ملغى':'مرحّل'}</td><td><button className="btn" onClick={()=>setEditing(r)}>فتح القيد</button></td></tr>)}</tbody></table></div>{!filtered.length&&<Empty text="لا توجد حركات مطابقة. أضف قيداً أو غيّر التصفية."/>}<PageNavigation page={current} pages={pages} total={filtered.length} onChange={setPage}/></>}</section>
 {editing&&<LedgerEditor key={editing.id} initial={editing} cases={cases} access={access} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);reload()}}/>}</>;
}
function LedgerEditor({initial,cases,access,onClose,onSaved}:{initial:LedgerRecord;cases:CaseSummary[];access:Permissions;onClose:()=>void;onSaved:()=>void}) {
 const [draft,setDraft]=useState(initial),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const set=(key:string,value:string)=>setDraft(r=>({...r,payload:{...r.payload,[key]:value}}));
 async function save(action:string){setBusy(true);setError('');try{await departmentRequest(action,{workspace:'accounting',record:draft,id:draft.id,revision:draft.revision,reason});toast.success(action==='void_record'?'حُفظ الإلغاء مع أصل القيد':'حُفظ القيد المالي');onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <EditorDialog title={draft.revision?'تفاصيل القيد':'قيد مالي جديد'} description="القيد المرحّل ثابت. لتصحيحه، ألغِه مع سبب واضح ثم أضف القيد الصحيح." busy={busy} onClose={onClose}>
 <form onSubmit={e=>{e.preventDefault();void save('save_record')}}><fieldset disabled={busy||!access.canEdit||!!draft.revision}><CasePicker cases={cases} value={draft.caseId} onChange={v=>setDraft(r=>({...r,caseId:v}))} optional={access.caseScope==='all'}/><div className="form-grid"><OfficeSelect label="نوع القيد" value={draft.payload.type} onChange={v=>set('type',v)} options={Object.entries(ENTRY_TYPES)}/><DateField label="تاريخ القيد" value={draft.payload.date} onChange={v=>set('date',v)}/><OfficeSelect label="عملة القيد" value={draft.payload.currency} onChange={v=>set('currency',v)} options={Object.keys(CURRENCIES).map(k=>[k,k])}/><Field label="المبلغ" value={draft.payload.amount} onChange={v=>set('amount',v)}/><Field label="مرجع القيد / رقم الإيصال" value={draft.payload.reference} onChange={v=>set('reference',v)}/><Field label="الدافع / المستفيد" value={draft.payload.party} onChange={v=>set('party',v)}/><Field label="ملاحظات القيد" value={draft.payload.notes} onChange={v=>set('notes',v)} multiline wide/></div><p className="subtitle">حتى {CURRENCIES[draft.payload.currency]} خانات عشرية. لا تُجمع عملات مختلفة.</p>{!draft.revision&&access.canEdit&&<button type="submit" className="btn primary" disabled={!draft.payload.amount||!draft.payload.reference||!draft.payload.party||!draft.payload.date||access.caseScope!=='all'&&!draft.caseId}>ترحيل القيد</button>}</fieldset></form>
 {draft.payload.status==='void'&&<p className="notice">سبب الإلغاء: {draft.payload.voidReason}</p>}
 {!!draft.revision&&access.canEdit&&draft.payload.status==='posted'&&<section className="void-entry"><h3>إلغاء القيد</h3><Field label="سبب إلغاء القيد" value={reason} onChange={setReason} multiline/><button className="btn" disabled={busy||!reason.trim()} onClick={()=>void save('void_record')}>تأكيد إلغاء القيد</button></section>}
 {error&&<p className="notice" role="alert">{error}</p>}{!!draft.revision&&<DepartmentHistory workspace="accounting" id={draft.id} revision={draft.revision}/>}<button className="btn" disabled={busy} onClick={onClose}>إغلاق القيد</button></EditorDialog>;
}
