import {useEffect,useRef,useState} from 'react';
import {Files,Plus,FileCheck2} from 'lucide-react';
import {toast} from 'sonner';
import {departmentRequest} from '@/lib/local-auth';
import {type CaseSummary,type CollectionData,type CollectionRecord,newDepartmentRecord} from '@/lib/departments';
import type {Permissions} from '@/lib/permissions';
import {blankDocument,amountInWords} from '@/lib/document-fields';
import {COLLECTION_FIELDS,missingDocumentFields} from '@/lib/collection-documents';
import {clientName} from '@/lib/clients';
import {normalizeSearch} from '@/lib/case-browse';
import {Field,DateField,Empty,saveBlob} from '../shared';
import {OfficeSelect,officeTime} from '../office-shared';
import PageNavigation from '../page-navigation';
import {CasePicker,DepartmentHistory,EditorDialog,StatusMessage,useRecords,exportCsv} from './shared';
export default function Collections({cases,access}:{cases:CaseSummary[];access:Permissions}) {
 const {rows,loading,error,reload}=useRecords<CollectionData>('collections');
 const [search,setSearch]=useState(''),[status,setStatus]=useState('active'),[page,setPage]=useState(1),[editing,setEditing]=useState<CollectionRecord|null>(null);
 const reviewed=(r:CollectionRecord)=>!!r.review&&r.review.caseRevision===cases.find(c=>c.id===r.caseId)?.revision&&r.review.recordRevision===r.revision;
 const filtered=rows.filter(r=>(status==='all'||status==='archived'?status==='all'||r.archived:!r.archived&&(status!=='review'||!reviewed(r)))&&normalizeSearch([r.payload.code,r.payload.company,r.payload.defendant,r.payload.civilId,r.payload.account].join(' ')).includes(normalizeSearch(search)));
 const pages=Math.max(1,Math.ceil(filtered.length/12)),current=Math.min(page,pages);
 return <><section className="department-hero"><div><div className="eyebrow">ملفات المطالبات</div><h1>التحصيل</h1><p>بيانات منظمة لكل قضية، ومصدر واضح لكل مستند.</p></div><Files size={64}/></section>
 <div className="department-metrics"><div><span>ملفات نشطة</span><b>{rows.filter(r=>!r.archived).length}</b></div><div><span>راجعت بياناتها الحالية</span><b>{rows.filter(r=>!r.archived&&reviewed(r)).length}</b></div><div><span>تحتاج مراجعة المصدر</span><b>{rows.filter(r=>!r.archived&&!reviewed(r)).length}</b></div></div>
 <section className="panel"><div className="department-toolbar"><Field label="بحث ملفات التحصيل" value={search} onChange={v=>{setSearch(v);setPage(1)}}/><OfficeSelect label="حالة الملف" value={status} onChange={v=>{setStatus(v);setPage(1)}} options={[['active','الملفات النشطة'],['review','تحتاج مراجعة'],['archived','المؤرشفة'],['all','كل الملفات']]}/><div className="actions">{access.canExport&&<button className="btn" onClick={()=>void exportCsv('collections','Mawatheeq-collections',[['الكود','الموكل','الخصم','القضية','المراجعة'],...filtered.map(r=>[r.payload.code,r.payload.company,r.payload.defendant,r.caseId,reviewed(r)?'راجعت البيانات الحالية':'تحتاج مراجعة'])]).catch(e=>toast.error(e.message))}>تصدير القائمة</button>}{access.canEdit&&<button className="btn primary" onClick={()=>setEditing(newDepartmentRecord('collections','file',{...blankDocument(),sourceReference:'',notes:''}))}><Plus size={17}/> ملف تحصيل جديد</button>}</div></div>
 <StatusMessage loading={loading} error={error}/>{!loading&&!error&&<><div className="collection-grid">{filtered.slice((current-1)*12,current*12).map(r=><article className="collection-card" key={r.id}><header><span className="collection-code">{r.payload.code||cases.find(c=>c.id===r.caseId)?.code||'بلا كود'}</span><span className={'tag '+(reviewed(r)?'green':'amber')}>{r.archived?'مؤرشف':reviewed(r)?'تمت المراجعة':'يحتاج مراجعة'}</span></header><h2>{r.payload.company||'موكل غير مكتمل'}</h2><p>ضد {r.payload.defendant||'طرف غير مكتمل'}</p><div className="collection-amount">{r.payload.amount||'—'} <small>د.ك</small></div><footer><small>نسخة {r.revision}</small><button className="btn" onClick={()=>setEditing(r)}>فتح الملف</button></footer></article>)}</div>{!filtered.length&&<Empty text="أضف ملفاً مرتبطاً بقضية وابدأ بإدخال البيانات من مصدرها."/>}<PageNavigation page={current} pages={pages} total={filtered.length} onChange={setPage}/></>}</section>
 {editing&&<CollectionEditor key={editing.id} initial={editing} cases={cases} access={access} onClose={()=>setEditing(null)} onChanged={reload}/>}</>;
}
function CollectionEditor({initial,cases,access,onClose,onChanged}:{initial:CollectionRecord;cases:CaseSummary[];access:Permissions;onClose:()=>void;onChanged:()=>void}) {
 const [saved,setSaved]=useState(initial),[draft,setDraft]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),[attested,setAttested]=useState(false),[outputs,setOutputs]=useState<{id:string;kind:string;recordRevision:number;templateVersion:string;createdAt:string;actor:string}[]>([]),[outputVersion,setOutputVersion]=useState(0);
 const intent=useRef<Record<string,string>>({});
 const dirty=JSON.stringify(draft)!==JSON.stringify(saved),c=cases.find(c=>c.id===draft.caseId);
 const reviewed=!!saved.review&&saved.review.recordRevision===saved.revision&&saved.review.caseRevision===c?.revision;
 const editable=access.canEdit&&!draft.archived;
 useEffect(()=>{let active=true;if(saved.revision)departmentRequest<typeof outputs>('outputs',{workspace:'collections',id:saved.id}).then(r=>{if(active)setOutputs(r)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[saved.id,saved.revision,outputVersion]);
 const set=(key:string,value:unknown)=>setDraft(r=>({...r,payload:{...r.payload,[key]:value,...(key==='amount'?{amountWords:amountInWords(String(value))}:{})}}));
 async function mutate(action:string,data:Record<string,unknown>){setBusy(true);setError('');try{const r=await departmentRequest<CollectionRecord>(action,{workspace:'collections',id:saved.id,revision:saved.revision,...data});setSaved(r);setDraft(r);setAttested(false);onChanged();toast.success('حُفظ ملف التحصيل')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function generate(kind:'claim'|'bundle'){setBusy(true);setError('');try{const key=saved.revision+kind;const outputId=intent.current[key]??=crypto.randomUUID();const output=await departmentRequest<{id:string;data:CollectionData;templateVersion:string}>('generate',{workspace:'collections',id:saved.id,revision:saved.revision,kind,outputId});if(output.templateVersion!=='office-word-v1')throw new Error('نسخة القالب غير مدعومة. حدّث الصفحة.');const {generateWord}=await import('@/lib/document-tools');saveBlob(await generateWord(kind,output.data),`Mawatheeq-${kind}-${output.id}.docx`);setOutputVersion(v=>v+1);toast.success('تم إعداد Word وحفظ نسخة بيانات الإنشاء')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <EditorDialog title={saved.revision?'ملف التحصيل':'ملف تحصيل جديد'} description="دوّن البيانات كما وردت في المصدر. الحقول غير المعروفة تبقى فارغة، وتُراجع البيانات قبل إنشاء المستندات." busy={busy} onClose={onClose}>
 <form onSubmit={e=>{e.preventDefault();void mutate('save_record',{record:draft})}}><fieldset disabled={busy||!editable}>
 <CasePicker cases={cases} value={draft.caseId} disabled={!!saved.revision} onChange={id=>{const c=cases.find(c=>c.id===id);setDraft(r=>({...r,caseId:id,payload:{...r.payload,code:c?.code||'',company:c?clientName(c):'',defendant:c?.opponent||''}}))}}/>
 {COLLECTION_FIELDS.map(([title,fields])=><section className="department-form-section" key={title}><h3>{title}</h3><div className="form-grid">{fields.map(([key,label])=>key.toLowerCase().includes('date')?<DateField key={key} label={label} value={String(draft.payload[key]||'')} onChange={v=>set(key,v)}/>:<Field key={key} label={label} value={String(draft.payload[key]||'')} onChange={v=>set(key,v)}/>)}</div></section>)}
 <p className="amount-words">{draft.payload.amountWords}</p>
 <section className="department-form-section"><h3>مستندات الحافظة</h3><p className="subtitle">أضف وصف المستندات المتوفرة فعلاً وحدد ما يدخل الحافظة. لا يلزم رفع PDF.</p>{draft.payload.evidence.map((e,i)=><div className="evidence-row" key={e.id}><label className="checkbox-line"><input type="checkbox" checked={e.included} onChange={ev=>set('evidence',draft.payload.evidence.map((x,j)=>j===i?{...x,included:ev.target.checked}:x))}/> تضمين المستند {i+1}</label><Field label={'وصف المستند '+(i+1)} value={e.description} onChange={v=>set('evidence',draft.payload.evidence.map((x,j)=>j===i?{...x,description:v}:x))}/><DateField label={'تاريخ المستند '+(i+1)} value={e.date} onChange={v=>set('evidence',draft.payload.evidence.map((x,j)=>j===i?{...x,date:v}:x))}/><Field label={'عدد صفحات المستند '+(i+1)} type="number" value={String(e.pages)} onChange={v=>set('evidence',draft.payload.evidence.map((x,j)=>j===i?{...x,pages:Number(v)}:x))}/><button type="button" className="text-link" onClick={()=>set('evidence',draft.payload.evidence.filter((_,j)=>j!==i))}>إزالة المستند {i+1}</button></div>)}{draft.payload.evidence.length<100&&<button type="button" className="btn" onClick={()=>set('evidence',[...draft.payload.evidence,{id:crypto.randomUUID(),included:true,date:'',description:'',pages:1}])}>إضافة مستند للحافظة</button>}</section>
 <Field label="مرجع المصدر الذي تمت مطابقته" value={draft.payload.sourceReference} onChange={v=>set('sourceReference',v)} placeholder="رقم الملف أو العقد، الجهة، وتاريخ الاطلاع"/><Field label="ملاحظات التحصيل" value={draft.payload.notes} onChange={v=>set('notes',v)} multiline/>
 {editable&&<button className="btn primary" type="submit" disabled={!draft.caseId||(!dirty&&!!saved.revision)}>حفظ ملف التحصيل</button>}</fieldset></form>
 {error&&<p role="alert" className="notice">{error}</p>}
 {!!saved.revision&&<><section className="collection-review"><h3><FileCheck2 size={20}/> مراجعة المصدر</h3><p>{reviewed?`راجع ${saved.review!.reviewer} هذه النسخة بتاريخ ${officeTime(saved.review!.createdAt)}`:'يحتاج الملف إلى مراجعة المصدر. تعديل الملف أو القضية يجعل المراجعة السابقة غير سارية.'}</p>{dirty&&<p className="notice">احفظ التعديلات قبل المراجعة أو الإنشاء.</p>}{editable&&<><label className="checkbox-line"><input type="checkbox" checked={attested} disabled={busy||dirty} onChange={e=>setAttested(e.target.checked)}/> راجعت البيانات الحالية وطابقتها مع المصدر المسجل.</label><button className="btn" disabled={busy||dirty||!attested||!saved.payload.sourceReference||!c} onClick={()=>void mutate('review_file',{caseRevision:c?.revision,attested:true})}>تسجيل مراجعة المصدر</button></>}</section>
 <section className="collection-outputs"><h3>إعداد المستندات</h3><p className="subtitle">القوالب الحالية لصحيفة المطالبة بعد رفض أمر الأداء وحافظة المستندات. الحقول المطلوبة أدناه خاصة بالقالب المختار.</p>{(['claim','bundle'] as const).map(kind=>{const missing=missingDocumentFields(saved.payload,kind);return <div className="output-option" key={kind}><strong>{kind==='claim'?'صحيفة الدعوى':'حافظة المستندات'}</strong><small>{missing.length?'الحقول المطلوبة: '+missing.join('، '):'حقول القالب مكتملة'}</small>{access.canExport&&<button className="btn primary" disabled={busy||dirty||!reviewed||saved.archived||!!missing.length} onClick={()=>void generate(kind)}>{kind==='claim'?'إنشاء صحيفة Word':'إنشاء حافظة Word'}</button>}</div>})}
 {!!outputs.length&&<details><summary>سجل نسخ الإنشاء ({outputs.length}{outputs.length===50?'+':''})</summary>{outputs.map(o=><p key={o.id}>{o.kind==='claim'?'صحيفة':'حافظة'} · نسخة الملف {o.recordRevision} · {o.actor} · {officeTime(o.createdAt)}</p>)}<small>حُفظت بيانات كل إنشاء مستقلة عن التعديلات اللاحقة.</small></details>}</section>
 {access.canEdit&&<button className="btn" disabled={busy||dirty} onClick={()=>void mutate('archive_record',{archived:!saved.archived})}>{saved.archived?'إعادة فتح الملف':'أرشفة الملف'}</button>}
 <DepartmentHistory workspace="collections" id={saved.id} revision={saved.revision}/></>}
 <button type="button" className="btn" disabled={busy} onClick={onClose}>إغلاق الملف</button></EditorDialog>;
}
