import {useState} from 'react';
import {UsersRound,Plus} from 'lucide-react';
import {toast} from 'sonner';
import {departmentRequest} from '@/lib/local-auth';
import {type DepartmentRecord,newDepartmentRecord,LEAVE_STATUSES} from '@/lib/departments';
import type {Permissions} from '@/lib/permissions';
import {todayISO,formatDate} from '@/lib/domain';
import {normalizeSearch} from '@/lib/case-browse';
import {Field,DateField,Empty} from '../shared';
import {OfficeSelect} from '../office-shared';
import PageNavigation from '../page-navigation';
import {DepartmentHistory,EditorDialog,StatusMessage,useRecords,exportCsv} from './shared';
export default function HR({access}:{access:Permissions}) {
 const {rows,loading,error,reload}=useRecords<Record<string,string>>('hr');
 const [tab,setTab]=useState<'employee'|'leave'>('employee'),[search,setSearch]=useState(''),[status,setStatus]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<DepartmentRecord|null>(null);
 const employees=rows.filter(r=>r.kind==='employee'),leaves=rows.filter(r=>r.kind==='leave');
 const employeeName=(id:string)=>employees.find(r=>r.id===id)?.payload.name||'غير متاح';
 const filtered=rows.filter(r=>r.kind===tab&&(!status||(status==='archived'?r.archived:!r.archived&&r.payload.status===status))&&normalizeSearch([r.payload.name,r.payload.employeeNumber,r.payload.department,r.payload.title,r.payload.type,employeeName(r.subjectId)].join(' ')).includes(normalizeSearch(search)));
 const pages=Math.max(1,Math.ceil(filtered.length/12)),current=Math.min(page,pages),today=todayISO();
 function add(kind:'employee'|'leave'){setEditing(newDepartmentRecord('hr',kind,kind==='employee'?{employeeNumber:'',name:'',title:'',department:'',phone:'',startDate:'',status:'active',notes:''}:{type:'سنوية',fromDate:today,toDate:today,status:'pending',notes:'',decisionNote:''} as Record<string,string>))}
 return <><section className="department-hero"><div><div className="eyebrow">فريق مواثيق</div><h1>الموارد البشرية</h1><p>ملفات الموظفين ومواعيد الإجازات في سجل مشترك.</p></div><UsersRound size={64}/></section>
 <div className="department-metrics"><div><span>الموظفون النشطون</span><b>{employees.filter(r=>!r.archived&&r.payload.status==='active').length}</b></div><div><span>طلبات بانتظار القرار</span><b>{leaves.filter(r=>r.payload.status==='pending').length}</b></div><div><span>في إجازة اليوم</span><b>{new Set(leaves.filter(r=>r.payload.status==='approved'&&r.payload.fromDate<=today&&r.payload.toDate>=today).map(r=>r.subjectId)).size}</b></div></div>
 <section className="panel"><div className="department-toolbar"><div className="department-tabs" role="group" aria-label="سجلات الموارد البشرية"><button className={'btn '+(tab==='employee'?'primary':'')} aria-pressed={tab==='employee'} onClick={()=>{setTab('employee');setStatus('');setPage(1)}}>ملفات الموظفين</button><button className={'btn '+(tab==='leave'?'primary':'')} aria-pressed={tab==='leave'} onClick={()=>{setTab('leave');setStatus('');setPage(1)}}>الإجازات</button></div>{access.canEdit&&<button className="btn primary" onClick={()=>add(tab)}><Plus size={17}/>{tab==='employee'?'موظف جديد':'طلب إجازة جديد'}</button>}</div>
 <div className="department-toolbar"><Field label="بحث الموارد البشرية" value={search} onChange={v=>{setSearch(v);setPage(1)}}/><OfficeSelect label="تصفية الحالة" value={status} onChange={v=>{setStatus(v);setPage(1)}} empty="جميع الحالات" options={tab==='employee'?[['active','نشط'],['inactive','غير نشط'],['archived','مؤرشف']]:Object.entries(LEAVE_STATUSES)}/>{access.canExport&&<button className="btn" onClick={()=>void exportCsv('hr','Mawatheeq-'+tab,tab==='employee'?[['رقم الموظف','الاسم','المسمى','القسم','تاريخ الانضمام','الحالة'],...filtered.map(r=>[r.payload.employeeNumber,r.payload.name,r.payload.title,r.payload.department,r.payload.startDate,r.archived?'مؤرشف':r.payload.status==='active'?'نشط':'غير نشط'])]:[['الموظف','نوع الإجازة','من','إلى','الحالة','ملاحظة القرار'],...filtered.map(r=>[employeeName(r.subjectId),r.payload.type,r.payload.fromDate,r.payload.toDate,LEAVE_STATUSES[r.payload.status as keyof typeof LEAVE_STATUSES],r.payload.decisionNote])]).catch(e=>toast.error(e.message))}>تصدير القائمة</button>}</div>
 <StatusMessage loading={loading} error={error}/>{!loading&&!error&&<>{tab==='employee'?<div className="people-grid">{filtered.slice((current-1)*12,current*12).map(r=><article className="person-card" key={r.id}><div className="person-avatar">{r.payload.name.slice(0,1)}</div><span className={'tag '+(!r.archived&&r.payload.status==='active'?'green':'')}>{r.archived?'مؤرشف':r.payload.status==='active'?'نشط':'غير نشط'}</span><h2>{r.payload.name}</h2><p>{r.payload.title||'المسمى غير مسجل'}</p><small>{r.payload.department||'قسم غير مسجل'} · {r.payload.employeeNumber}</small><button className="btn" onClick={()=>setEditing(r)}>فتح ملف الموظف</button></article>)}</div>:<div className="table-wrap"><table className="office-table"><thead><tr><th>الموظف</th><th>نوع الإجازة</th><th>المدة</th><th>الحالة</th><th>التفاصيل</th></tr></thead><tbody>{filtered.slice((current-1)*12,current*12).map(r=><tr key={r.id}><td>{employeeName(r.subjectId)}</td><td>{r.payload.type}</td><td>{formatDate(r.payload.fromDate)} — {formatDate(r.payload.toDate)}</td><td><span className={'tag '+(r.payload.status==='approved'?'green':'amber')}>{LEAVE_STATUSES[r.payload.status as keyof typeof LEAVE_STATUSES]}</span></td><td><button className="btn" onClick={()=>setEditing(r)}>فتح طلب الإجازة</button></td></tr>)}</tbody></table></div>}{!filtered.length&&<Empty text={tab==='employee'?'أضف ملف الموظف وبيانات عمله الأساسية.':'أضف طلب إجازة لموظف مسجل.'}/>}<PageNavigation page={current} pages={pages} total={filtered.length} onChange={setPage}/></>}
 <p className="subtitle">ملف الموظف مستقل عن حساب الدخول. إنشاء الحسابات ومنح صلاحياتها من إعدادات مسؤول المكتب.</p></section>
 {editing&&<HREditor key={editing.id} initial={editing} employees={employees} access={access} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);reload()}}/>}</>;
}
function HREditor({initial,employees,access,onClose,onSaved}:{initial:DepartmentRecord;employees:DepartmentRecord[];access:Permissions;onClose:()=>void;onSaved:()=>void}) {
 const [draft,setDraft]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const employee=draft.kind==='employee',editable=access.canEdit&&!draft.archived;
 const set=(key:string,value:string)=>setDraft(r=>({...r,payload:{...r.payload,[key]:value}}));
 async function save(action:string){setBusy(true);setError('');try{await departmentRequest(action,{workspace:'hr',record:draft,id:draft.id,revision:draft.revision,archived:!draft.archived});toast.success('حُفظ سجل الموارد البشرية');onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <EditorDialog title={employee?(draft.revision?'ملف الموظف':'موظف جديد'):'طلب إجازة'} description={employee?'بيانات العمل الأساسية ووسيلة الاتصال.':'يسجل القرار في سجل التغييرات، ولا تقبل إجازتان معتمدتان متداخلتان للموظف.'} busy={busy} onClose={onClose}>
 <form onSubmit={e=>{e.preventDefault();void save('save_record')}}><fieldset disabled={busy||!editable}><div className="form-grid">{employee?<>{[['employeeNumber','الرقم الوظيفي'],['name','اسم الموظف'],['title','المسمى الوظيفي'],['department','القسم'],['phone','هاتف الموظف']].map(([k,label])=><Field key={k} label={label} value={draft.payload[k]} onChange={v=>set(k,v)}/>)}<DateField label="تاريخ الانضمام" value={draft.payload.startDate} onChange={v=>set('startDate',v)}/><OfficeSelect label="حالة الموظف" value={draft.payload.status} onChange={v=>set('status',v)} options={[['active','نشط'],['inactive','غير نشط']]}/></>:<><fieldset disabled={!!draft.revision}><OfficeSelect label="الموظف" value={draft.subjectId} onChange={v=>setDraft(r=>({...r,subjectId:v}))} empty="اختر الموظف" options={employees.filter(r=>!r.archived||r.id===draft.subjectId).map(r=>[r.id,r.payload.name+' · '+r.payload.employeeNumber])}/></fieldset><Field label="نوع الإجازة" value={draft.payload.type} onChange={v=>set('type',v)}/><DateField label="بداية الإجازة" value={draft.payload.fromDate} onChange={v=>set('fromDate',v)}/><DateField label="نهاية الإجازة" value={draft.payload.toDate} onChange={v=>set('toDate',v)}/><OfficeSelect label="قرار الإجازة" value={draft.payload.status} onChange={v=>set('status',v)} options={Object.entries(LEAVE_STATUSES)}/><Field label="ملاحظة القرار / السبب" value={draft.payload.decisionNote} onChange={v=>set('decisionNote',v)}/></>}<Field label="ملاحظات الموظف أو الطلب" value={draft.payload.notes} onChange={v=>set('notes',v)} multiline wide/></div>
 {editable&&<button type="submit" className="btn primary" disabled={employee?(!draft.payload.name||!draft.payload.employeeNumber):(!draft.subjectId||!draft.payload.fromDate||!draft.payload.toDate)}>حفظ سجل الموارد البشرية</button>}</fieldset></form>
 {error&&<p className="notice" role="alert">{error}</p>}{employee&&!!draft.revision&&access.canEdit&&<button className="btn" disabled={busy} onClick={()=>void save('archive_record')}>{draft.archived?'إعادة فتح ملف الموظف':'أرشفة ملف الموظف'}</button>}{!!draft.revision&&<DepartmentHistory workspace="hr" id={draft.id} revision={draft.revision}/>}<button className="btn" disabled={busy} onClick={onClose}>إغلاق السجل</button></EditorDialog>;
}
