'use client';
import {useState} from 'react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Save,Plus,Archive,RotateCcw,LoaderCircle,ShieldCheck} from 'lucide-react';
import {CaseRecord,Rules,caseState,EXECUTION_NOTES,TYPES,formatDate,todayISO} from '@/lib/domain';
import {Field,DateField,Choice,Badge,api} from './shared';
import {toast} from 'sonner';
export default function CaseDetail({record,rules,onClose,onSaved}:{record:CaseRecord;rules:Rules;onClose:()=>void;onSaved:(c:CaseRecord)=>void}){
 const [c,setC]=useState<CaseRecord>({...record,outcome:caseState(record,rules).outcome}),[busy,setBusy]=useState(false),[proc,setProc]=useState({date:todayISO(),text:'',lawyer:'',followup:''});const st=caseState(c,rules);const set=(key:string,value:unknown)=>setC(x=>({...x,[key]:value}));
 async function save(archive?:boolean){setBusy(true);try{const d=await api('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({case:{...c,...(archive!==undefined?{archived:archive}:{})}})});setC(d.case);onSaved(d.case);toast.success('تم حفظ السجل وتحديث القوائم');if(archive!==undefined)onClose()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 const field=(key:string,label:string,wide=false,multiline=false)=><Field key={key} label={label} value={String(c[key]||'')} onChange={v=>set(key,v)} wide={wide} multiline={multiline}/>;
 return <Sheet open onOpenChange={v=>!v&&onClose()}><SheetContent side="left" className="detail-sheet" dir="rtl"><SheetHeader className="sheet-header"><div className="eyebrow">CASE FILE · {c.code||'NEW'}</div><SheetTitle>{c.client||'إضافة حكم جديد'}</SheetTitle><SheetDescription>{c.opponent||'أدخل بيانات القضية ثم احفظ السجل'}</SheetDescription><div className="actions" style={{marginTop:15}}><Badge value={st.outcome}/><Badge value={st.status}/>{c.insurance&&<span className="tag"><ShieldCheck size={13}/> تأمين</span>}</div></SheetHeader>
 <Tabs defaultValue="case" dir="rtl"><TabsList className="detail-tabs"><TabsTrigger value="case">بيانات الحكم</TabsTrigger><TabsTrigger value="execution">الطعن والتنفيذ</TabsTrigger><TabsTrigger value="history">سجل الإجراءات</TabsTrigger><TabsTrigger value="source">المصدر</TabsTrigger></TabsList>
 <TabsContent value="case"><div className="form-grid" style={{marginTop:20}}>{field('code','كود المكتب')}{field('autoNumber','الرقم الآلي')}{field('client','الموكل')}{field('opponent','الخصم')}{field('clientGroup','الموكل الموحد للتحليل')}{field('role','صفة الموكل')}<label className="field"><span>نوع الحكم</span><Choice value={c.type} onChange={v=>set('type',v)} options={TYPES}/></label><DateField label="تاريخ الحكم" value={c.date} onChange={v=>set('date',v)}/><label className="field"><span>نتيجة الحكم</span><Choice value={c.outcome} onChange={v=>set('outcome',v)} options={['لصالحنا','غير صالحنا','غير محدد']}/></label>{field('lawyer','المحامي')}{field('ruling','منطوق الحكم',true,true)}{field('caseNumber','رقم القضية / السنة')}{field('court','المحكمة والدائرة')}{field('subject','موضوع الدعوى',true,true)}{field('notes','ملاحظات',true,true)}<label className="checkbox-line"><Checkbox checked={c.insurance} onCheckedChange={v=>set('insurance',v===true)}/> سجل تأمين مرتبط بالأحكام</label></div></TabsContent>
 <TabsContent value="execution"><div className="detail-summary" style={{margin:'20px 0'}}><div><small>نهاية مهلة الطعن</small><b className="mono">{formatDate(st.due)}</b></div><div><small>موعد التنفيذ من الحكم</small><b className="mono">{formatDate(st.executionDue)}</b></div><div><small>إدراج في قائمة التنفيذ</small><b>{st.criminal?'جنح':st.eligible?'نعم':'لا'}</b></div><div><small>حالة الطعن المعتمدة</small><Badge value={st.appeal}/></div></div><div className="notice">اختر «لا يوجد» بعد تأكيد عدم اتخاذ الخصم إجراء. الخانة الفارغة لا تُعد تأكيداً.</div><div className="form-grid"><label className="field"><span>تأكيد إجراء الخصم</span><Choice value={c.appealConfirmation} onChange={v=>set('appealConfirmation',v)} options={['لا يوجد','تم','غير مؤكد']}/></label><label className="field"><span>الطعن المسجل</span><Choice value={c.appealRecorded} onChange={v=>set('appealRecorded',v)} options={Array.from(new Set(['تم','لا يوجد','مؤجل','لم ينجز','منتهي',c.appealRecorded]))}/></label><label className="field wide"><span>ملاحظات التنفيذ المعتمدة</span><Choice value={c.executionNote} onChange={v=>set('executionNote',v)} options={EXECUTION_NOTES}/></label><label className="field"><span>تأكيد عدم اتخاذ أي إجراء للإغلاق</span><Choice value={c.noActionConfirmation} onChange={v=>set('noActionConfirmation',v)} options={['نعم','لا']}/></label><label className="field"><span>حكم غيابي؟</span><Choice value={String(c.absent||'')} onChange={v=>set('absent',v)} options={['نعم','لا']}/></label>{[['copyDate','استلام الصيغة التنفيذية'],['notificationDate','إعلان الصيغة'],['announcementDate','بداية الإعلان'],['originalDate','صورة الأصل']].map(([key,label])=><DateField key={key} label={label} value={String(c[key]||'')} onChange={v=>set(key,v)}/>)}{field('executionStage','مرحلة التنفيذ',true)}{field('executionLegacy','تفاصيل التنفيذ',true,true)}</div></TabsContent>
 <TabsContent value="history"><h3 className="section-title">إضافة إجراء</h3><div className="form-grid"><DateField label="تاريخ الإجراء" value={proc.date} onChange={v=>setProc(p=>({...p,date:v}))}/><Field label="المسؤول" value={proc.lawyer} onChange={v=>setProc(p=>({...p,lawyer:v}))}/><Field label="تفاصيل الإجراء" value={proc.text} onChange={v=>setProc(p=>({...p,text:v}))} wide multiline/><DateField label="موعد المتابعة" value={proc.followup} onChange={v=>setProc(p=>({...p,followup:v}))}/></div><button className="btn" style={{margin:'16px 0 25px'}} onClick={()=>{if(!proc.text.trim()){toast.error('أدخل تفاصيل الإجراء');return}set('procedures',[...c.procedures,{...proc,id:crypto.randomUUID(),source:'إدخال يدوي'}]);setProc({date:todayISO(),text:'',lawyer:'',followup:''});toast.info('أُضيف الإجراء. اضغط حفظ لتثبيته.')}}><Plus/> إضافة إلى السجل</button><div className="timeline">{[...c.procedures].reverse().map(p=><div className="timeline-item" key={p.id}><small>{formatDate(p.date)} {p.lawyer&&' · '+p.lawyer}</small><p>{p.text}</p>{p.source&&<small>{p.source}</small>}</div>)}{!c.procedures.length&&<p className="muted">لا توجد إجراءات مسجلة بعد.</p>}</div></TabsContent>
 <TabsContent value="source"><h3 className="section-title">مراجع ومراجعة البيانات</h3><div className="form-grid">{field('source','مرجع المصدر',true,true)}{field('review','نتيجة مراجعة الحكم',true,true)}{field('matchReview','ملاحظات المطابقة',true,true)}{field('lawyerSource','مرجع اسم المحامي',true,true)}{field('legacyNotes','ملاحظات التنفيذ السابقة المحفوظة',true,true)}</div><p className="subtitle">معرف السجل: <span className="mono">{c.id}</span></p></TabsContent></Tabs>
 <div className="detail-actions"><button className="btn primary" onClick={()=>save()} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Save/>} حفظ التغييرات</button><AlertDialog><AlertDialogTrigger asChild><button className="btn">{c.archived?<RotateCcw/>:<Archive/>}{c.archived?'استعادة':'أرشفة السجل'}</button></AlertDialogTrigger><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>{c.archived?'استعادة السجل؟':'أرشفة السجل؟'}</AlertDialogTitle><AlertDialogDescription>يبقى السجل محفوظاً، ويمكن استعادته من الأرشيف في أي وقت.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>إلغاء</AlertDialogCancel><AlertDialogAction onClick={()=>save(!c.archived)}>تأكيد</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>
 </SheetContent></Sheet>
}
