'use client';
import {useState} from 'react';
import {Sheet,SheetContent,SheetHeader,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Checkbox} from '@/components/ui/checkbox';
import {AlertDialog,AlertDialogTrigger,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Save,Plus,Archive,RotateCcw,LoaderCircle,ShieldCheck} from 'lucide-react';
import {CaseRecord,Rules,caseState,EXECUTION_NOTES,TYPES,formatDate,todayISO,elapsedDaysLabel} from '@/lib/domain';
import {Field,DateField,Choice,Badge,api} from './shared';
import {toast} from 'sonner';
import {RemainingDays} from './case-timing';
import {ClientSelect,ClientEditor} from './client-directory';
import {emptyClient,enrichCase,clientName,type ClientEntity} from '@/lib/clients';
import CaseVerification from './case-verification';
import {sharedBackend} from '@/lib/client-api';
export default function CaseDetail({record,rules,clients,initialTab='case',canEdit=true,canEditClients=true,lockClientLinks=false,canVerify=true,canEditVerification=true,canEditDocuments=true,canManageReviews=false,onOfficeChanged=()=>{},asOf=todayISO(),onClientSaved,onClose,onSaved}:{record:CaseRecord;rules:Rules;clients:ClientEntity[];initialTab?:string;canEdit?:boolean;canEditClients?:boolean;lockClientLinks?:boolean;canVerify?:boolean;canEditVerification?:boolean;canEditDocuments?:boolean;canManageReviews?:boolean;onOfficeChanged?:()=>void;asOf?:string;onClientSaved:(c:ClientEntity)=>void;onClose:()=>void;onSaved:(c:CaseRecord)=>void}){
 const [newClient,setNewClient]=useState<ClientEntity|null>(null);
 const [c,setC]=useState<CaseRecord>({...record,client:record.client||clients.find(e=>e.id===record.clientEntityId)?.name||'',clientGroup:record.clientGroup||clients.find(e=>e.id===record.clientEntityId)?.name||'',outcome:caseState(record,rules).outcome}),[busy,setBusy]=useState(false),[proc,setProc]=useState({date:todayISO(),text:'',lawyer:'',followup:''});const st=caseState(c,rules,asOf);const set=(key:string,value:unknown)=>setC(x=>({...x,[key]:value}));
 const [savedCase,setSavedCase]=useState(c);const dirty=JSON.stringify(c)!==JSON.stringify(savedCase);
 const entity=clients.find(x=>x.id===c.clientEntityId);
 const selectClient=(id:string)=>{const e=clients.find(x=>x.id===id);setC(old=>({...old,clientEntityId:id,clientContactId:'',client:c.revision?old.client:e?.name||'',clientGroup:c.revision?old.clientGroup:e?.name||''}))};
 async function save(archive?:boolean){if(!canEdit)return;if(!c.clientEntityId){toast.error('اختر ملف الموكل أولاً أو أضف موكلاً جديداً');return}setBusy(true);try{const d=await api('/api/cases',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({case:{...c,...(archive!==undefined?{archived:archive}:{})}})});const saved=enrichCase(d.case,clients);setC(saved);setSavedCase(saved);onSaved(saved);toast.success('تم حفظ السجل وتحديث القوائم');if(archive!==undefined)onClose()}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 const field=(key:string,label:string,wide=false,multiline=false)=><Field key={key} label={label} value={String(c[key]||'')} onChange={v=>set(key,v)} wide={wide} multiline={multiline}/>;
 return <><Sheet open onOpenChange={v=>!v&&onClose()}><SheetContent side="left" className="detail-sheet" dir="rtl"><SheetHeader className="sheet-header"><div className="eyebrow">CASE FILE · {c.code||'NEW'}</div><SheetTitle>{entity?.name||clientName(c)||'إضافة قضية جديدة'}</SheetTitle><SheetDescription>{c.opponent||'أدخل بيانات القضية ثم احفظ السجل'}</SheetDescription><div className="actions" style={{marginTop:15}}><Badge value={st.outcome}/><Badge value={st.status}/>{c.insurance&&<span className="tag"><ShieldCheck size={13}/> تأمين</span>}</div></SheetHeader>
 {c.importReview&&<p className="notice">توجد معلومات من Excel تحتاج مراجعة في تبويب «المصدر». بقيت القيم السابقة محفوظة.</p>}<section aria-label="مدد القضية"><p className="subtitle" style={{marginBottom:10}}>الأيام التقويمية بحسب {formatDate(asOf)}</p><div className="detail-summary"><div><small>منذ الحكم</small><b>{elapsedDaysLabel(st.elapsed)}</b></div><div><small>المتبقي للطعن</small><RemainingDays days={st.remaining} final={st.days===0} warning={rules.warning}/></div><div><small>المتبقي للتنفيذ من الحكم</small><RemainingDays days={st.executionRemaining} warning={rules.warning}/></div></div></section>{!canEdit&&<p className="notice">هذا الملف للقراءة فقط حسب صلاحيات حسابك.</p>}<Tabs defaultValue={initialTab==='verification'&&!canVerify?'case':initialTab} dir="rtl"><TabsList className="detail-tabs"><TabsTrigger value="case">بيانات الحكم</TabsTrigger><TabsTrigger value="execution">الطعن والتنفيذ</TabsTrigger><TabsTrigger value="history">سجل الإجراءات</TabsTrigger><TabsTrigger value="source">المصدر</TabsTrigger>{sharedBackend&&canVerify&&<TabsTrigger value="verification">التحقق والمصادر</TabsTrigger>}</TabsList>
 <TabsContent value="case"><fieldset className="readonly-fields" disabled={!canEdit}><div className="form-grid" style={{marginTop:20}}>{field('code','كود المكتب')}{field('autoNumber','الرقم الآلي')}<fieldset className="readonly-fields wide" disabled={lockClientLinks}><ClientSelect clients={clients} value={c.clientEntityId||''} onChange={selectClient} onCreate={canEditClients?()=>setNewClient(emptyClient()):undefined}/>
 {entity&&canEditClients&&<button type="button" className="text-link wide" onClick={()=>setNewClient(entity)}>إدارة ملف الموكل وإضافة الأشخاص المرتبطين به</button>}</fieldset>
 <label className="field"><span>طالب الدعوى / مسؤول المتابعة لدى الموكل</span><select disabled={lockClientLinks} value={c.clientContactId||''} onChange={e=>set('clientContactId',e.target.value)}><option value="">غير محدد</option>{entity?.contacts.map(p=><option key={p.id} value={p.id}>{p.name}{p.role?' · '+p.role:''}</option>)}</select></label>
 {field('casePerson','الشخص المعني بهذه القضية (إن وجد)')}{field('casePersonRole','صلة الشخص المعني بالموكل')}{field('opponent','الخصم')}
 {entity?.needsReview&&<div className="notice wide">ملف هذا الموكل يحتاج مراجعة. تبقى الصيغة السابقة محفوظة في تبويب المصدر.</div>}
{field('role','صفة الموكل')}<label className="field"><span>نوع الحكم</span><Choice value={c.type} onChange={v=>set('type',v)} options={TYPES}/></label><DateField label="تاريخ الحكم" value={c.date} onChange={v=>set('date',v)}/><label className="field"><span>نتيجة الحكم</span><Choice value={c.outcome} onChange={v=>set('outcome',v)} options={['لصالحنا','غير صالحنا','غير محدد']}/></label>{field('lawyer','المحامي')}{field('ruling','منطوق الحكم',true,true)}{field('caseNumber','رقم القضية / السنة')}{field('court','المحكمة والدائرة')}{field('subject','موضوع الدعوى',true,true)}{field('notes','ملاحظات',true,true)}<label className="checkbox-line"><Checkbox checked={c.insurance||entity?.sector==='insurance'} disabled={entity?.sector==='insurance'} onCheckedChange={v=>set('insurance',v===true)}/> قضية تأمين</label><label className="checkbox-line"><Checkbox checked={Boolean(c.executionFile)} onCheckedChange={v=>set('executionFile',v===true)}/> ملف تنفيذ</label><label className="checkbox-line"><Checkbox checked={Boolean(c.telecom)||entity?.sector==='telecom'} disabled={entity?.sector==='telecom'} onCheckedChange={v=>set('telecom',v===true)}/> قضية اتصالات</label><p className="subtitle wide">قضايا موكل قطاعه «اتصالات» أو «تأمين» تظهر تلقائياً في قسمه. تصنيف التنفيذ لا يؤكد انتهاء مهلة الطعن أو جاهزية التنفيذ.</p></div></fieldset></TabsContent>
 <TabsContent value="execution"><fieldset className="readonly-fields" disabled={!canEdit}><div className="detail-summary" style={{margin:'20px 0'}}><div><small>نهاية مهلة الطعن</small><b className="mono">{formatDate(st.due)}</b></div><div><small>موعد التنفيذ من الحكم</small><b className="mono">{formatDate(st.executionDue)}</b></div><div><small>إدراج في قائمة التنفيذ</small><b>{c.executionFile?'ملف تنفيذ مسجل':st.criminal?'جنح':st.eligible?'نعم':'لا'}</b></div><div><small>حالة الطعن المعتمدة</small><Badge value={st.appeal}/></div></div><div className="notice">اختر «لا يوجد» بعد تأكيد عدم اتخاذ الخصم إجراء. الخانة الفارغة لا تُعد تأكيداً.</div><div className="form-grid"><label className="field"><span>تأكيد إجراء الخصم</span><Choice value={c.appealConfirmation} onChange={v=>set('appealConfirmation',v)} options={['لا يوجد','تم','غير مؤكد']}/></label><label className="field"><span>الطعن المسجل</span><Choice value={c.appealRecorded} onChange={v=>set('appealRecorded',v)} options={Array.from(new Set(['تم','لا يوجد','مؤجل','لم ينجز','منتهي',c.appealRecorded]))}/></label><label className="field wide"><span>ملاحظات التنفيذ المعتمدة</span><Choice value={c.executionNote} onChange={v=>set('executionNote',v)} options={EXECUTION_NOTES}/></label><label className="field"><span>تأكيد عدم اتخاذ أي إجراء للإغلاق</span><Choice value={c.noActionConfirmation} onChange={v=>set('noActionConfirmation',v)} options={['نعم','لا']}/></label><label className="field"><span>حكم غيابي؟</span><Choice value={String(c.absent||'')} onChange={v=>set('absent',v)} options={['نعم','لا']}/></label>{[['copyDate','استلام الصيغة التنفيذية'],['notificationDate','إعلان الصيغة'],['announcementDate','بداية الإعلان'],['executionOpenDate','فتح ملف التنفيذ'],['executionProcedureDate','إجراءات التنفيذ'],['originalDate','صورة الأصل']].map(([key,label])=><DateField key={key} label={label} value={String(c[key]||'')} onChange={v=>set(key,v)}/>)}{field('executionStage','مرحلة التنفيذ',true)}{field('executionLegacy','تفاصيل التنفيذ',true,true)}</div></fieldset></TabsContent>
 <TabsContent value="history"><fieldset className="readonly-fields" disabled={!canEdit}><h3 className="section-title">إضافة إجراء</h3><div className="form-grid"><DateField label="تاريخ الإجراء" value={proc.date} onChange={v=>setProc(p=>({...p,date:v}))}/><Field label="المسؤول" value={proc.lawyer} onChange={v=>setProc(p=>({...p,lawyer:v}))}/><Field label="تفاصيل الإجراء" value={proc.text} onChange={v=>setProc(p=>({...p,text:v}))} wide multiline/><DateField label="موعد المتابعة" value={proc.followup} onChange={v=>setProc(p=>({...p,followup:v}))}/></div><button className="btn" style={{margin:'16px 0 25px'}} onClick={()=>{if(!proc.text.trim()){toast.error('أدخل تفاصيل الإجراء');return}set('procedures',[...c.procedures,{...proc,id:crypto.randomUUID(),source:'إدخال يدوي'}]);setProc({date:todayISO(),text:'',lawyer:'',followup:''});toast.info('أُضيف الإجراء. اضغط حفظ لتثبيته.')}}><Plus/> إضافة إلى السجل</button><div className="timeline">{[...c.procedures].reverse().map(p=><div className="timeline-item" key={p.id}><small>{formatDate(p.date)} {p.lawyer&&' · '+p.lawyer}</small><p>{p.text}</p>{p.kind&&<small>{p.kind} · </small>}{p.source&&<small>{p.source}</small>}{p.followup&&<small style={{display:'block'}}>موعد المتابعة: {formatDate(p.followup)}</small>}</div>)}{!c.procedures.length&&<p className="muted">لا توجد إجراءات مسجلة بعد.</p>}</div></fieldset></TabsContent>
 <TabsContent value="source"><fieldset className="readonly-fields" disabled={!canEdit}><h3 className="section-title">مراجع ومراجعة البيانات</h3><div className="notice">صيغة الموكل الأصلية: {c.client||'غير مسجلة'}<br/>التجميع السابق: {c.clientGroup||'غير مسجل'}</div><div className="form-grid">{field('source','مرجع المصدر',true,true)}{field('review','نتيجة مراجعة الحكم',true,true)}{field('matchReview','ملاحظات المطابقة',true,true)}{field('lawyerSource','مرجع اسم المحامي',true,true)}{field('legacyNotes','ملاحظات التنفيذ السابقة المحفوظة',true,true)}{c.importReview&&field('importReview','معلومات Excel المحفوظة للمراجعة',true,true)}</div><p className="subtitle">معرف السجل: <span className="mono">{c.id}</span></p></fieldset></TabsContent>{sharedBackend&&canVerify&&<TabsContent value="verification"><CaseVerification canEdit={canEditVerification} canEditDocuments={canEditDocuments} record={c} dirty={dirty} canManage={canManageReviews} onChanged={onOfficeChanged}/></TabsContent>}</Tabs>
 {canEdit&&<div className="detail-actions"><button className="btn primary" onClick={()=>save()} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Save/>} حفظ التغييرات</button><AlertDialog><AlertDialogTrigger asChild><button className="btn">{c.archived?<RotateCcw/>:<Archive/>}{c.archived?'استعادة':'أرشفة السجل'}</button></AlertDialogTrigger><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>{c.archived?'استعادة السجل؟':'أرشفة السجل؟'}</AlertDialogTitle><AlertDialogDescription>يبقى السجل محفوظاً، ويمكن استعادته من الأرشيف في أي وقت.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>إلغاء</AlertDialogCancel><AlertDialogAction onClick={()=>save(!c.archived)}>تأكيد</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>}
 </SheetContent></Sheet>{newClient&&<ClientEditor entity={newClient} clients={clients} onClose={()=>setNewClient(null)} onSaved={e=>{onClientSaved(e);setC(old=>({...old,clientEntityId:e.id,clientContactId:old.clientEntityId===e.id?old.clientContactId:'',client:c.revision?old.client:e.name,clientGroup:c.revision?old.clientGroup:e.name}))}}/>}</>
}
