'use client';
import {useEffect,useState} from 'react';
import {toast} from 'sonner';
import {officeRequest} from '@/lib/local-auth';
import {getDocumentUrl} from '@/lib/client-api';
import {type CaseRecord,formatDate} from '@/lib/domain';
import {type CaseFile,type Evidence,type ReviewScope,EVIDENCE_KINDS,SOURCE_TYPES,SCOPE_LABELS,reviewStatus} from '@/lib/office';
import {api,Field,DateField} from './shared';
import {OfficeSelect,ReviewBadge,RecordHistory,officeTime} from './office-shared';

type SavedDocument={id:string;filename:string;fileKey:string|null};
export default function CaseVerification({record,dirty,canManage,onChanged}:{record:CaseRecord;dirty:boolean;canManage:boolean;onChanged:()=>void}) {
 const [file,setFile]=useState<CaseFile|null>(null),[docs,setDocs]=useState<SavedDocument[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loaded,setLoaded]=useState(0);
 const [upload,setUpload]=useState<File|null>(null),[documentId,setDocumentId]=useState(''),[kind,setKind]=useState<keyof typeof EVIDENCE_KINDS>('judgment'),[reference,setReference]=useState(''),[pages,setPages]=useState('');
 const [scope,setScope]=useState<ReviewScope>('judgment'),[decision,setDecision]=useState('needs_review'),[notes,setNotes]=useState(''),[chosen,setChosen]=useState<string[]>([]),[confirmed,setConfirmed]=useState(false),[noticeDate,setNoticeDate]=useState(''),[method,setMethod]=useState(''),[recipient,setRecipient]=useState(''),[result,setResult]=useState('');
 const [sourceType,setSourceType]=useState('court_record'),[sourceReference,setSourceReference]=useState('');
 const [preview,setPreview]=useState<{url:string;name:string}|null>(null);
 const load=async()=>{setError('');setConfirmed(false);setPreview(null);try{const [next,documents]=await Promise.all([officeRequest<CaseFile>('case_file',{caseId:record.id}),api('/api/documents')]);setFile(next);setDocs(documents.documents.filter((d:SavedDocument)=>d.fileKey));setConfirmed(false);setLoaded(n=>n+1)}catch(e){setError((e as Error).message)}};
 useEffect(()=>{if(record.revision)void load()},[record.id,record.revision]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview.url)},[preview]);
 useEffect(()=>{setConfirmed(false)},[scope,decision,chosen,notes,noticeDate,method,recipient,result,sourceType,sourceReference,record.revision]);
 const disabled=busy||dirty||!record.revision||!!record.archived;
 const chooseDocument=(id:string)=>{setDocumentId(id);setUpload(null);const e=file?.evidence.find(x=>x.documentId===id);if(e){setKind(e.kind);setReference(e.reference);setPages(e.pages)}};
 async function attach(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{
  let id=documentId;
  if(upload){const form=new FormData();form.set('file',upload);form.set('filename',upload.name);form.set('payload',JSON.stringify({purpose:'case-evidence',caseId:record.id}));const saved=await api('/api/documents',{method:'POST',body:form});id=saved.id;setDocumentId(id);setDocs(d=>[...d,{id,filename:upload.name,fileKey:saved.fileKey||'saved'}]);setUpload(null)}
  const previous=file?.evidence.find(e=>e.documentId===id);
  await officeRequest('link_evidence',{caseId:record.id,documentId:id,kind,reference,pages,revision:previous?.revision||0});setReference('');setPages('');setDocumentId('');await load();onChanged();toast.success('تم ربط المستند بالقضية');
 }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function review(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{await officeRequest('review',{caseId:record.id,caseRevision:record.revision,scope,decision,notes,evidenceIds:chosen,evidenceVersions:Object.fromEntries((file?.evidence||[]).filter(e=>chosen.includes(e.id)).map(e=>[e.id,{linkRevision:e.revision,documentRevision:e.documentRevision}])),confirmed,noticeDate,method,recipient,result,sourceType,sourceReference});setNotes('');setChosen([]);setConfirmed(false);await load();onChanged();toast.success(decision==='verified'?'حُفظ الاعتماد ومراجعه':'سُجل طلب المراجعة')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function openDocument(id:string,name:string){setBusy(true);setError('');try{setPreview({url:await getDocumentUrl(id),name})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 if(!record.revision)return <p className="notice">احفظ القضية أولاً لربط المستندات وتسجيل المراجعة.</p>;
 return <div className="office-verification">
  <p className="notice">وجود تاريخ أو ملاحظة لا يثبت صحة البيانات. الاعتماد مراجعة بشرية للمصدر المحدد، ويسجل باسم المستخدم الحالي. إدخال القضايا ومراجعتها لا يتطلب رفع PDF؛ المرفقات اختيارية. تعديل القضية أو مرجع المستند يُبطل صلاحية الاعتماد السابق.</p>
  {dirty&&<p role="status" className="notice">توجد تغييرات غير محفوظة. احفظ القضية قبل ربط المستندات أو اعتماد المراجعة.</p>}{record.archived&&<p className="notice">القضية مؤرشفة. استعدها قبل إضافة مراجعة.</p>}
  {error&&<div className="notice" role="alert">{error} <button className="text-link" onClick={()=>void load()}>إعادة التحميل</button></div>}
  {!file?<p role="status">جارٍ تحميل سجل التحقق…</p>:<>
  <div className="office-cards">{(['judgment','announcement'] as ReviewScope[]).map(s=><div className="office-card" key={s}><h3>{SCOPE_LABELS[s]}</h3><ReviewBadge status={reviewStatus(record,file.latestReviews,s)}/></div>)}</div>
  <details className="office-attachments"><summary>مرفقات اختيارية (إن وجدت)</summary><section><h3>المرفقات المرتبطة</h3>{!file.evidence.length&&<p className="muted">لم تُرفق مستندات إثبات بهذه القضية بعد.</p>}{file.evidence.map(e=><div className="evidence-row" key={e.id}><div><strong>{e.filename}</strong><p>{EVIDENCE_KINDS[e.kind]} · {e.reference}{e.pages&&` · صفحات ${e.pages}`}</p></div><div className="actions"><button className="btn" disabled={busy} onClick={()=>void openDocument(e.documentId,e.filename)}>فتح PDF</button><button className="text-link" disabled={disabled} onClick={()=>chooseDocument(e.documentId)}>تعديل المرجع</button></div></div>)}</section>
  {preview&&<section className="pdf-evidence"><div className="actions"><strong>{preview.name}</strong><a className="btn" href={preview.url} download={preview.name}>تنزيل PDF</a><button className="btn" onClick={()=>setPreview(null)}>إغلاق المستند</button></div><iframe src={preview.url} title={'مستند الإثبات: '+preview.name}/></section>}
  <form className="office-form" onSubmit={attach}><h3>إضافة مرفق اختياري أو تعديل مرجعه</h3><fieldset disabled={disabled}><div className="form-grid"><label className="field wide"><span>رفع مستند PDF (حتى 25 ميغابايت)</span><input key={upload?.name||documentId||'empty'} type="file" accept="application/pdf,.pdf" onChange={e=>{setUpload(e.target.files?.[0]||null);setDocumentId('')}}/></label>{upload&&<p className="subtitle wide">الملف المختار: {upload.name}</p>}<OfficeSelect label="أو اختر PDF محفوظاً" value={documentId} onChange={chooseDocument} options={docs.map(d=>[d.id,d.filename])} empty="اختر مستنداً"/><OfficeSelect label="نوع الإثبات" value={kind} onChange={v=>setKind(v as Evidence['kind'])} options={Object.entries(EVIDENCE_KINDS)}/><Field label="مرجع المستند / جهة الإصدار" value={reference} onChange={setReference}/><Field label="صفحات الإثبات" value={pages} onChange={setPages} placeholder="مثال: 1–3"/></div><button className="btn" type="submit" disabled={!reference.trim()||(!upload&&!documentId)}>حفظ رابط المستند</button></fieldset></form>
  </details>
  <form className="office-form" onSubmit={review}><h3>تسجيل نتيجة المراجعة</h3><fieldset disabled={disabled}><div className="form-grid"><OfficeSelect label="نطاق المراجعة" value={scope} onChange={v=>{setScope(v as ReviewScope);setChosen([])}} options={Object.entries(SCOPE_LABELS)}/><OfficeSelect label="قرار المراجعة" value={decision} onChange={setDecision} options={[['needs_review','يحتاج مراجعة'],...(canManage?[['verified','اعتماد بعد المطابقة'] as [string,string]]:[])]}/></div>
  {!canManage&&<p className="subtitle">يمكنك طلب مراجعة وإضافة المستندات؛ الاعتماد لمسؤول المكتب.</p>}
  {decision==='verified'&&<><p className="subtitle">{scope==='judgment'?'طابق الرقم الآلي والأطراف وتاريخ الحكم ونوعه ومنطوقه ونتيجته مع المستند.':'طابق إعلان الصيغة التنفيذية مع مستند الإعلان؛ اعتماد الحكم لا يعتمد الإعلان تلقائياً.'}</p><fieldset className="evidence-choices"><legend>مرفقات مستخدمة في المراجعة (اختياري)</legend>{file.evidence.filter(e=>e.kind===scope||e.kind==='both').map(e=><label className="checkbox-line" key={e.id}><input type="checkbox" checked={chosen.includes(e.id)} onChange={event=>setChosen(ids=>event.target.checked?[...ids,e.id]:ids.filter(id=>id!==e.id))}/>{e.filename} · {e.reference} {e.pages&&`(ص ${e.pages})`}</label>)}{!file.evidence.some(e=>e.kind===scope||e.kind==='both')&&<p className="subtitle">يمكن تسجيل مرجع المصدر أدناه دون رفع مرفق.</p>}</fieldset>
  <div className="form-grid"><OfficeSelect label="مصدر التحقق" value={sourceType} onChange={setSourceType} options={Object.entries(SOURCE_TYPES)}/><Field label="مرجع المصدر الذي تمت مراجعته" value={sourceReference} onChange={setSourceReference} placeholder="رقم السجل أو الطلب أو المستند، والجهة / الصفحة"/></div>
  {scope==='announcement'&&<><p className="subtitle">تاريخ إعلان الصيغة المحفوظ: {formatDate(record.notificationDate)}. صحح تاريخ القضية في تبويب الطعن والتنفيذ قبل الاعتماد عند الحاجة.</p><div className="form-grid"><DateField label="تاريخ الإعلان بالمستند" value={noticeDate} onChange={setNoticeDate}/><Field label="وسيلة الإعلان" value={method} onChange={setMethod}/><Field label="المعلن إليه / المستلم" value={recipient} onChange={setRecipient}/><Field label="نتيجة الإعلان بالمستند" value={result} onChange={setResult}/></div></>}
  </>}
  <Field label="ملاحظات المطابقة أو سبب طلب المراجعة" value={notes} onChange={setNotes} multiline/>{decision==='verified'&&<label className="checkbox-line"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>راجعت المصدر المحدد وطابقت بيانات {SCOPE_LABELS[scope]} في هذه النسخة.</label>}
  <button className="btn primary" type="submit" disabled={!notes.trim()||(decision==='verified'&&(!confirmed||!sourceReference.trim()))}>{busy?'جارٍ الحفظ…':decision==='verified'?'حفظ الاعتماد':'حفظ طلب المراجعة'}</button></fieldset></form>
  <section className="office-history"><h3>سجل المراجعات</h3>{file.reviews.length===50&&<p className="subtitle">آخر 50 مراجعة؛ السجل الكامل ضمن نسخة البيانات في الإعدادات.</p>}{file.reviews.map(r=><details key={r.id}><summary>{SCOPE_LABELS[r.scope]} · {r.decision==='needs_review'?'طلب مراجعة':r.current&&r.caseRevision===record.revision?'اعتماد سارٍ':'اعتماد سابق'} · {r.reviewer} · {officeTime(r.createdAt)}</summary><p>نسخة القضية عند المراجعة: {r.caseRevision}</p><p className="preserve-lines">{r.details.notes}</p>{r.details.sourceReference&&<p>{SOURCE_TYPES[r.details.sourceType as keyof typeof SOURCE_TYPES]} · {r.details.sourceReference}</p>}{r.scope==='announcement'&&r.decision==='verified'&&<p>{formatDate(r.details.noticeDate||'')} · {r.details.method} · {r.details.recipient} · {r.details.result}</p>}{r.evidence.map(e=><p key={e.id}>{e.filename} · {e.reference} · صفحات {e.pages||'غير محددة'} · نسخة المستند {e.documentRevision}</p>)}</details>)}{!file.reviews.length&&<p className="muted">لا توجد مراجعة مسجلة. البيانات القديمة لم تعتمد تلقائياً.</p>}</section>
  <RecordHistory key={loaded} initial={file.history} action="case_history" data={{caseId:record.id}}/>
  </>}
 </div>;
}
