'use client';
import {useState} from 'react';
import {toast} from 'sonner';
import {officeRequest} from '@/lib/local-auth';
import type {OfficeContext,Member} from '@/lib/office';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';

export default function OfficeStaff({context,onChanged}:{context:OfficeContext;onChanged:()=>void}) {
 const [editing,setEditing]=useState<Member|'new'|null>(null),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const open=(m:Member|'new')=>{setUsername('');setPassword('');setError('');setEditing(m)};
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await officeRequest(editing==='new'?'create_member':'reset_member_password',editing==='new'?{username,password}:{id:(editing as Member).id,password});setPassword('');setEditing(null);onChanged();toast.success('تم حفظ الحساب. يلزم تغيير كلمة المرور عند الدخول.')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function toggle(m:Member){if(!window.confirm(m.enabled?`إيقاف حساب ${m.username} وإنهاء جلساته الحالية؟`:`إعادة تفعيل حساب ${m.username}؟`))return;setBusy(true);try{await officeRequest('set_member_enabled',{id:m.id,enabled:!m.enabled});onChanged();toast.success('تم تحديث حالة الحساب')}catch(e){toast.error((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel office-staff"><div className="panel-head"><div><h2>فريق المكتب والصلاحيات</h2><p className="panel-note">أسماء مستخدمين محلية؛ لا يتطلب الموظفون بريداً إلكترونياً أو حساباً خارجياً.</p></div>{context.canManage&&<button className="btn primary" onClick={()=>open('new')}>إضافة موظف</button>}</div><div className="panel-body"><p className="subtitle">مسؤول المكتب يعتمد المراجعات ويدير المستخدمين. الموظف يعدل القضايا، ويرفق الأدلة، ويطلب المراجعة، ويتابع أعمال المكتب. جميع الأعضاء لديهم وصول إلى ملفات المكتب.</p><div className="table-wrap"><table className="office-table"><thead><tr><th>اسم المستخدم</th><th>الصلاحية</th><th>الحالة</th>{context.canManage&&<th>إدارة الحساب</th>}</tr></thead><tbody>{context.members.map(m=><tr key={m.id}><td dir="ltr">{m.username}</td><td>{m.role==='owner'?'مسؤول المكتب':'موظف'}</td><td>{m.enabled?'فعال':'موقوف'}{m.mustChangePassword?' · يلزم تغيير كلمة المرور':''}</td>{context.canManage&&<td>{m.role==='editor'&&<div className="actions"><button className="btn" disabled={busy} onClick={()=>open(m)}>كلمة مرور مؤقتة</button><button className="btn" disabled={busy} onClick={()=>void toggle(m)}>{m.enabled?'إيقاف الحساب':'إعادة تفعيل'}</button></div>}</td>}</tr>)}</tbody></table></div></div>
 {editing&&<Dialog open onOpenChange={v=>{if(!v&&!busy){setEditing(null);setPassword('')}}}><DialogContent dir="rtl"><DialogHeader><DialogTitle>{editing==='new'?'إضافة موظف':'إعادة تعيين كلمة مرور '+editing.username}</DialogTitle><DialogDescription>امنح الموظف كلمة المرور المؤقتة بنفسك. سيُطلب تغييرها عند الدخول؛ إعادة التعيين تنهي الجلسات السابقة.</DialogDescription></DialogHeader><form className="office-form" onSubmit={save}><fieldset disabled={busy}>{editing==='new'&&<label className="field"><span>اسم المستخدم الجديد</span><input dir="ltr" value={username} onChange={e=>setUsername(e.target.value)} required pattern="[A-Za-z0-9][A-Za-z0-9_.\-]{2,31}" autoComplete="off"/><small>3–32 حرفاً إنجليزياً أو رقماً أو . _ -</small></label>}<label className="field"><span>كلمة المرور المؤقتة</span><input type="password" dir="ltr" value={password} onChange={e=>setPassword(e.target.value)} minLength={12} required autoComplete="new-password"/><small>12 حرفاً على الأقل؛ يغيّرها الموظف عند أول دخول.</small></label>{error&&<p className="notice" role="alert">{error}</p>}<button className="btn primary" type="submit">{busy?'جارٍ الحفظ…':'حفظ الحساب'}</button></fieldset></form></DialogContent></Dialog>}
 </section>;
}
