'use client';
import {useEffect,useMemo,useState} from 'react';
import {type CaseRecord,formatDate,todayISO} from '@/lib/domain';
import {clientName} from '@/lib/clients';
import {normalizeSearch} from '@/lib/case-browse';
import {type OfficeData,type ReviewScope,type ReviewStatus,SCOPE_LABELS,REVIEW_LABELS,reviewStatus,workBucket} from '@/lib/office';
import {OfficeSelect,ReviewBadge,officeTime} from './office-shared';
import {Field,Empty} from './shared';
import PageNavigation from './page-navigation';

export type ReviewSelection={scope:ReviewScope;status:ReviewStatus|''};
export function OfficeSummary({records,data,onReview,onWork}:{records:CaseRecord[];data:OfficeData;onReview:(selection:ReviewSelection)=>void;onWork:()=>void}) {
 const active=records.filter(c=>!c.archived),approved=active.filter(c=>reviewStatus(c,data.reviews,'judgment')==='verified').length,announced=active.filter(c=>reviewStatus(c,data.reviews,'announcement')==='verified').length;
 const today=todayISO(),attention=data.work.filter(w=>['overdue','today'].includes(workBucket(w,today))).length;
 return <section className="office-summary" aria-label="التحقق وأعمال المكتب"><div><h2>وضوح البيانات والمتابعة</h2><p>التحليل يشمل كل السجلات النشطة. الاعتماد أدناه مراجعة بشرية موثقة بالمصدر، ولا ينشأ من إدخال تاريخ أو ملاحظة.</p></div><div className="office-cards"><button className="office-card" onClick={()=>onReview({scope:'judgment',status:'verified'})}><span>بيانات أحكام معتمدة بالمراجعة</span><b>{approved}<small> / {active.length}</small></b></button><button className="office-card" onClick={()=>onReview({scope:'judgment',status:''})}><span>مركز التحقق من القضايا</span><b>{active.length-approved}<small> لم تعتمد حالياً</small></b></button><button className="office-card" onClick={()=>onReview({scope:'announcement',status:'verified'})}><span>إعلانات تنفيذ معتمدة بالمراجعة</span><b>{announced}</b></button><button className="office-card" onClick={onWork}><span>أعمال اليوم والمتأخرة</span><b>{attention}</b></button></div><small className="muted">آخر تحديث للمراجعات: {officeTime(data.loadedAt)}</small></section>;
}
export default function OfficeVerification({records,data,initial,onOpenCase}:{records:CaseRecord[];data:OfficeData;initial:ReviewSelection;onOpenCase:(record:CaseRecord)=>void}) {
 const [scope,setScope]=useState<ReviewScope>(initial.scope),[status,setStatus]=useState<string>(initial.status),[search,setSearch]=useState(''),[recorded,setRecorded]=useState(''),[page,setPage]=useState(1);
 const active=useMemo(()=>records.filter(c=>!c.archived).map(record=>({record,status:reviewStatus(record,data.reviews,scope)})),[records,data.reviews,scope]);
 const filtered=active.filter(x=>(!status||x.status===status)&&(!recorded||((recorded==='yes')===!!String(x.record.notificationDate||'').trim()))&&normalizeSearch([x.record.code,x.record.autoNumber,clientName(x.record),x.record.opponent].join(' ')).includes(normalizeSearch(search)));
 useEffect(()=>setPage(1),[scope,status,search,recorded]);
 const pages=Math.max(1,Math.ceil(filtered.length/20)),current=Math.min(page,pages);
 return <><div className="page-head"><div><div className="eyebrow">CASE / VERIFICATION</div><h1>التحقق من القضايا</h1><p className="subtitle">راجع مصدر كل سجل من داخل ملفه. اعتماد بيانات الحكم واعتماد إعلان التنفيذ قراران مستقلان.</p></div></div><div className="notice">المراجعة مسؤولية المراجع الذي يطابق المصدر. هذه الحالة لا تعني اتصالاً تلقائياً بالمحكمة أو تأكيداً آلياً لصحة الإعلان قانوناً. رفع PDF اختياري.</div><div className="office-toolbar"><OfficeSelect label="ما الذي نتحقق منه؟" value={scope} onChange={v=>{setScope(v as ReviewScope);setRecorded('');setStatus('')}} options={Object.entries(SCOPE_LABELS)}/><Field label="البحث عن سجل للمراجعة" value={search} onChange={setSearch}/><OfficeSelect label="حالة المراجعة" value={status} onChange={setStatus} options={Object.entries(REVIEW_LABELS)} empty="كل الحالات"/>{scope==='announcement'&&<OfficeSelect label="تاريخ الإعلان في القضية" value={recorded} onChange={setRecorded} options={[["yes","يوجد تاريخ مسجل"],["no","لا يوجد تاريخ مسجل"]]} empty="جميع السجلات"/>}</div>
 <div className="office-cards">{(Object.keys(REVIEW_LABELS) as ReviewStatus[]).map(s=><button className={'office-card '+(status===s?'selected':'')} key={s} onClick={()=>{setStatus(s);setRecorded('');setSearch('')}}><span>{REVIEW_LABELS[s]}</span><b>{active.filter(x=>x.status===s).length}</b></button>)}</div><section className="panel"><div className="panel-head"><h2>{SCOPE_LABELS[scope]} · {filtered.length} سجل</h2><p className="panel-note">يشمل السجلات النشطة؛ افتح الأرشيف من سجل الأحكام لمراجعة تاريخه.</p></div>{scope==='announcement'&&<p className="notice">تاريخ إعلان مسجل في {active.filter(x=>String(x.record.notificationDate||'').trim()).length} سجل. وجود التاريخ وحده لا يمنحه حالة الاعتماد.</p>}{!filtered.length?<Empty/>:<div className="table-wrap"><table className="office-table"><thead><tr><th>الكود / الرقم الآلي</th><th>الموكل والخصم</th><th>{scope==='judgment'?'تاريخ الحكم':'إعلان الصيغة المسجل'}</th><th>التحقق</th><th>ملف القضية</th></tr></thead><tbody>{filtered.slice((current-1)*20,current*20).map(({record:c,status:s})=><tr key={c.id}><td>{c.code||'—'}<small>{c.autoNumber||'بلا رقم آلي'}</small></td><td><strong>{clientName(c)}</strong><small>{c.opponent}</small></td><td>{formatDate(scope==='judgment'?c.date:c.notificationDate)}</td><td><ReviewBadge status={s}/></td><td><button className="btn" onClick={()=>onOpenCase(c)}>فتح التحقق</button></td></tr>)}</tbody></table></div>}<PageNavigation page={current} pages={pages} total={filtered.length} onChange={setPage}/></section></>;
}
