'use client';
import {useId,useState} from 'react';
import {officeRequest} from '@/lib/local-auth';
import {changedFields,REVIEW_LABELS,type ReviewStatus,type Change} from '@/lib/office';
export function OfficeSelect({label,value,onChange,options,empty}:{label:string;value:string;onChange:(value:string)=>void;options:[string,string][];empty?:string}) {
 const labelId=useId();
 return <label className="field"><span id={labelId}>{label}</span><select aria-labelledby={labelId} value={value} onChange={e=>onChange(e.target.value)}>{empty!==undefined&&<option value="">{empty}</option>}{options.map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>;
}
export function ReviewBadge({status}:{status:ReviewStatus}) {return <span className={'tag '+(status==='verified'?'green':status==='unreviewed'?'':'amber')}>{REVIEW_LABELS[status]}</span>}
export function officeTime(value:string) {return new Date(value).toLocaleString('ar-KW',{timeZone:'Asia/Kuwait',dateStyle:'medium',timeStyle:'short'})}
const fieldLabels:Record<string,string>={id:'معرّف السجل',code:'كود المكتب',autoNumber:'الرقم الآلي',client:'الموكل الأصلي',clientGroup:'تجميع الموكل الأصلي',clientEntityId:'ملف الموكل',clientContactId:'الشخص المتابع',casePerson:'الشخص المعني',casePersonRole:'صلته بالموكل',opponent:'الخصم',role:'صفة الموكل',type:'نوع الحكم',date:'تاريخ الحكم',outcome:'نتيجة الحكم',lawyer:'المحامي',ruling:'منطوق الحكم',caseNumber:'رقم القضية',court:'المحكمة',subject:'موضوع الدعوى',notes:'ملاحظات',insurance:'تأمين',telecom:'اتصالات',executionFile:'ملف تنفيذ',appealConfirmation:'تأكيد إجراء الخصم',appealRecorded:'الطعن المسجل',executionNote:'ملاحظات التنفيذ',noActionConfirmation:'تأكيد عدم اتخاذ إجراء',absent:'غيابي',copyDate:'استلام الصيغة',notificationDate:'إعلان الصيغة',announcementDate:'بداية الإعلان',executionOpenDate:'فتح التنفيذ',executionProcedureDate:'إجراء التنفيذ',originalDate:'صورة الأصل',executionStage:'مرحلة التنفيذ',executionLegacy:'التنفيذ السابق',procedures:'الإجراءات',source:'مرجع المصدر',review:'المراجعة السابقة',matchReview:'ملاحظات المطابقة',lawyerSource:'مرجع المحامي',legacyNotes:'ملاحظات سابقة',importReview:'مراجعة الاستيراد',archived:'مؤرشف',title:'العنوان',kind:'نوع الموعد',dueDate:'التاريخ',dueTime:'الوقت',assigneeId:'الموظف المسؤول',priority:'الأولوية',status:'الحالة',location:'المكان',completionNote:'نتيجة العمل',caseId:'القضية المرتبطة'};
function valueText(v:unknown):string {if(v===null||v===undefined||v==='')return '—';if(typeof v==='boolean')return v?'نعم':'لا';if(Array.isArray(v))return v.map(valueText).join('\n')||'—';if(typeof v==='object')return Object.entries(v as Record<string,unknown>).filter(([k])=>k!=='id').map(([k,x])=>(fieldLabels[k]||k)+': '+valueText(x)).join(' · ');return String(v)}
export function RecordHistory({initial,action,data,request=officeRequest}:{initial:Change[];action:string;data:Record<string,unknown>;request?:typeof officeRequest}) {
 const [rows,setRows]=useState(initial),[more,setMore]=useState(initial.length===50),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <section className="office-history"><h3>سجل التغييرات</h3><p className="subtitle">يسجل اسم المستخدم ووقت الحفظ والقيم قبل التعديل وبعده، منذ تفعيل هذه الميزة. الأوقات بتوقيت المكتب.</p>{!rows.length&&<p className="muted">لا توجد تغييرات مسجلة بعد تفعيل السجل.</p>}{rows.map(row=><details key={row.id}><summary>نسخة {row.revision} · {row.actor||'تحديث بيانات'} · {officeTime(row.createdAt)}</summary><div className="table-wrap"><table className="office-diff"><thead><tr><th>الحقل</th><th>قبل</th><th>بعد</th></tr></thead><tbody>{changedFields(row.before,row.after).map(key=><tr key={key}><th>{fieldLabels[key]||key}</th><td>{valueText(row.before?.[key])}</td><td>{valueText(row.after[key])}</td></tr>)}</tbody></table></div></details>)}{error&&<p role="alert" className="notice">{error}</p>}{more&&<button className="btn" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{const next=await request<Change[]>(action,{...data,offset:rows.length});setRows([...rows,...next]);setMore(next.length===50)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}>عرض تغييرات أقدم</button>}</section>;
}
