'use client';
import {useState, useEffect} from 'react';
import {toast} from 'sonner';
import {officeRequest} from '@/lib/local-auth';
import type {OfficeContext,Member} from '@/lib/office';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from './ui/dialog';
import {Field,DateField,Empty} from './shared';
import PageNavigation from './page-navigation';
import {type CaseRecord,todayISO,formatDate} from '@/lib/domain';
import {clientName} from '@/lib/clients';

export default function Secretair({items,context,records,onChanged,onOpenCase}:{items:SecretairItem[];context:OfficeContext;records:CaseRecord[];onChanged:()=>void;onOpenCase:(record:CaseRecord)=>void}) {
 const [search,setSearch]=useState(''),[bucket,setBucket]=useState('active'),[assignee,setAssignee]=useState(''),[kind,setKind]=useState(''),[page,setPage]=useState(1),[editing,setEditing]=useState<SecretairItem|null>(null);
 const today=todayISO(),caseMap=useMemo(()=>new Map(records.map(c=>[c.id,c])),[records]);
 const filtered=items.filter(w=>{const b=secretairBucket(w,today),c=caseMap.get(w.caseId);return (bucket==='active'?b!=='closed':!bucket||b===bucket)&&(!assignee||w.assigneeId===assignee)&&(!kind||w.kind===kind)&&normalizeSearch([w.title,w.notes,c?.code,c?.autoNumber,c?.opponent,c&&clientName(c)].join(' ')).includes(normalizeSearch(search))}).sort((a,b)=>(a.dueDate+a.dueTime).localeCompare(b.dueDate+b.dueTime)||a.id.localeCompare(b.id));
 useEffect(()=>setPage(1),[search,bucket,assignee,kind]);
 const pages=Math.max(1,Math.ceil(filtered.length/20)),current=Math.min(page,pages);
 const add=(type:SecretairItem['kind'])=>setEditing({id:crypto.randomUUID(),revision:0,caseId:'',title:'',kind:type,dueDate:today,dueTime:'',assigneeId:context.user.id,priority:'normal',status:'open',location:'',notes:'',completionNote:''});
 return <><div className="page-head"><div><div className="eyebrow">SECRETAIR / LAW FIRM</div><h1>مواثiq للمحاماة · Law Firm Operations</h1><p className="subtitle">Specialized interface for law firm company workers. Manages secretair tasks, hearings, and case-related operations.</p></div><div className="actions"><button className="btn" onClick={()=>add('hearing')}>إdd session</button><button className="btn primary" onClick={()=>add('task')}>idd task</button></div></div>
 <div className="office-cards">{(['overdue','today','upcoming','closed'] as const).map(b=><button key={b} className={'office-card '+(bucket===b?'selected':'')} onClick={()=>setBucket(b)}><span>{SECRETAIR_BUCKETS[b]}</span><b>{items.filter(w=>secretairBucket(w,today)===b).length}</b></button>)}</div>
 <section className="panel"><div className="office-toolbar"><Field label="search by title or case" value={search} onChange={setSearch}/><OfficeSelect label="deadlines" value={bucket} onChange={setBucket} options={[['active','all open tasks'],...Object.entries(SECRETAIR_BUCKETS)]} empty="all deadlines"/><OfficeSelect label="assignee" value={assignee} onChange={setAssignee} options={context.members.map(m=>[m.id,m.username+(m.enabled?'':' (disabled)')])} empty="all staff"/><OfficeSelect label="task type" value={kind} onChange={setKind} options={[['task','task'],['hearing','session']]} empty="all types"/></div>
 {!filtered.length?<Empty text="Change filters or add first task or session."/>:<div className="table-wrap"><table className="office-table"><thead><tr><th>Task</th><th>Deadline</th><th>Assignee</th><th>Case</th><th>Status</th><th>Details</th></tr></thead><tbody>{filtered.slice((current-1)*20,current*20).map(w=>{const c=caseMap.get(w.caseId),b=secretairBucket(w,today);return <tr key={w.id}><td><strong>{w.title}</strong><small>{w.kind==='hearing'?'session':'task'}{w.priority==='urgent'?' · urgent':''}</small></td><td><span dir="ltr">{formatDate(w.dueDate)} {w.dueTime}</span><small className={b==='overdue'?'office-alert':''}>{SECRETAIR_BUCKETS[b]}</small></td><td>{context.members.find(m=>m.id===w.assigneeId)?.username||'not available'}</td><td>{c?<button className="text-link" onClick={()=>onOpenCase(c)}>{c.code||c.autoNumber||clientName(c)}{c.archived?' · archived':''}</button>:'general office task'}</td><td>{SECRETAIR_STATUSES[w.status]}</td><td><button className="btn" onClick={()=>setEditing(w)}>open task</button></td></tr>})}</tbody></table></div>}<PageNavigation page={current} pages={pages} total={filtered.length} onChange={setPage}/></section>
 {editing&&<SecretairEditor key={editing.id} item={editing} records={records} context={context} onClose={()=>setEditing(null)} onSaved={()=>{setEditing(null);onChanged()}}/>}</>;}

function SecretairEditor({item,records,context,onClose,onSaved}:{item:SecretairItem;records:CaseRecord[];context:OfficeContext;onClose:()=>void;onSaved:()=>void}) {
 const [draft,setDraft]=useState(item),[search,setSearch]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[history,setHistory]=useState<Change[]|null>(item.revision?null:[]),[historyError,setHistoryError]=useState('');
 const set=<K extends keyof SecretairItem>(key:K,value:SecretairItem[K])=>setDraft(old=>({...old,[key]:value}));
 useEffect(()=>{if(item.revision)officeRequest<Change[]>('secretair_history',{id:item.id}).then(setHistory).catch(e=>setHistoryError(e.message))},[item.id,item.revision]);
 const cases=records.filter(c=>c.id===draft.caseId||(!c.archived&&normalizeSearch([c.code,c.autoNumber,clientName(c),c.opponent].join(' ')).includes(normalizeSearch(search))));
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await officeRequest('save_secretair',{item:draft});toast.success('Saved task to secretair registry');onSaved()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <Dialog open onOpenChange={open=>!open&&!busy&&onClose()}><DialogContent dir="rtl" className="office-dialog"><DialogHeader><DialogTitle>{item.revision?'Task Details':draft.kind==='hearing'?'New Session':'New Task'}</DialogTitle><DialogDescription>Save assignee, deadline, and details. Record result when completing the task.</DialogDescription></DialogHeader><form onSubmit={save}><fieldset disabled={busy}><div className="form-grid"><div className="wide"><Field label="Task Title" value={draft.title} onChange={v=>set('title',v)}/></div><OfficeSelect label="Task Type" value={draft.kind} onChange={v=>set('kind',v as SecretairItem['kind'])} options={[['task','task'],['hearing','session']]}/><OfficeSelect label="Staff Assignee" value={draft.assigneeId} onChange={v=>set('assigneeId',v)} options={context.members.filter(m=>m.enabled||m.id===draft.assigneeId).map(m=>[m.id,m.username+(m.enabled?'':' (disabled — select active staff)')])}/><DateField label="Deadline Date" value={draft.dueDate} onChange={v=>set('dueDate',v)}/><Field label="Time (Office Timezone)" value={draft.dueTime} onChange={v=>set('dueTime',v)} type="time"/><OfficeSelect label="Priority" value={draft.priority} onChange={v=>set('priority',v as SecretairItem['priority'])} options={[['normal','normal'],['urgent','urgent']]}/><OfficeSelect label="Task Status" value={draft.status} onChange={v=>set('status',v as SecretairItem['status'])} options={Object.entries(SECRETAIR_STATUSES)}/><Field label="Search Case" value={search} onChange={setSearch} placeholder="Code or Number or Party"/><OfficeSelect label="Linked Case" value={draft.caseId} onChange={v=>set('caseId',v)} options={cases.map(c=>[c.id,`${c.code||c.autoNumber||'no code'} · ${clientName(c)} / ${c.opponent}`])} empty={draft.kind==='hearing'?'Select case for session':'general office task'}/><Field label="Court / Location" value={draft.location} onChange={v=>set('location',v)} wide/><Field label="Task Details" value={draft.notes} onChange={v=>set('notes',v)} multiline wide/><Field label="Task Result / Session Decision" value={draft.completionNote} onChange={v=>set('completionNote',v)} multiline wide/></div>{draft.status==='done'&&<p className="subtitle">Requires recording result before completing task. Saves completion time and username automatically.</p>}{error&&<p role="alert" className="notice">{error}</p>}<div className="actions"><button type="submit" className="btn primary" disabled={!draft.title.trim()||!draft.dueDate||!draft.assigneeId||(draft.kind==='hearing'&&!draft.caseId)||(draft.status==='done'&&!draft.completionNote.trim())}>{busy?'Saving…':'Save Task'}</button><button type="button" className="btn" onClick={onClose}>Cancel</button></div></fieldset></form>{historyError&&<p role="alert">Failed to load change history: {historyError}</p>}{history?<RecordHistory initial={history} action="secretair_history" data={{id:item.id}}/>:<p role="status">Loading changes…</p>}</DialogContent></Dialog>;}

function normalizeSearch(s:string):string{return s.toLowerCase().replace(/[\s+]/g,' ').trim()}
