'use client';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {FileSearch} from 'lucide-react';
import {useEffect,useState} from 'react';
import {requestData} from '@/lib/client-api';
export function Choice({value,onChange,options,label,className=''}:{value:string;onChange:(s:string)=>void;options:string[];label?:string;className?:string}){return <Select dir="rtl" value={value||'__empty'} onValueChange={s=>onChange(s==='__empty'?'':s)}><SelectTrigger className={className} aria-label={label||'اختيار'}><SelectValue/></SelectTrigger><SelectContent><SelectItem value="__empty">{label||'غير مسجل'}</SelectItem>{options.filter(Boolean).map(s=><SelectItem value={s} key={s}>{s}</SelectItem>)}</SelectContent></Select>}
export function Field({label,value,onChange,wide=false,multiline=false,placeholder='',type='text'}:{label:string;value:string;onChange:(s:string)=>void;wide?:boolean;multiline?:boolean;placeholder?:string;type?:string}){return <label className={'field '+(wide?'wide':'')}><span>{label}</span>{multiline?<textarea value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>:<input type={type} value={value||''} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</label>}
export function DateField({label,value,onChange}:{label:string;value:string;onChange:(s:string)=>void}){const fmt=(v:string)=>/^\d{4}-\d{2}-\d{2}$/.test(v)?v.split('-').reverse().join('/'):v;const [text,setText]=useState(fmt(value));useEffect(()=>setText(fmt(value)),[value]);return <label className="field"><span>{label}</span><input dir="ltr" placeholder="DD/MM/YYYY" value={text} onChange={e=>{const s=e.target.value;setText(s);const m=s.match(/^(\d{2})\/(\d{2})\/(\d{4})$/);onChange(m?`${m[3]}-${m[2]}-${m[1]}`:s)}}/></label>}
export function Badge({value}:{value:string}){const tone=['لصالحنا','جاهز للتنفيذ','لا يوجد'].includes(value)?'green':['غير صالحنا','انتهت المهلة','جنح'].includes(value)?'red':/بانتظار|غير مؤكد|بيانات|خمسة/.test(value)?'amber':'wine';return <span className={'tag '+tone}>{value||'غير محدد'}</span>}
export function Empty({title='لا توجد نتائج',text='جرّب تعديل البحث أو عوامل التصفية.'}:{title?:string;text?:string}){return <div className="empty-state"><FileSearch/><h3>{title}</h3><p>{text}</p></div>}
export function Count({value}:{value:number}){const [v,setV]=useState(0);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setV(value);return}let frame:number;const start=performance.now();const step=(now:number)=>{const t=Math.min(1,(now-start)/650);setV(Math.round(value*(1-Math.pow(1-t,3))));if(t<1)frame=requestAnimationFrame(step)};frame=requestAnimationFrame(step);return()=>cancelAnimationFrame(frame)},[value]);return <>{v.toLocaleString('en-US')}</>}
export const api=requestData;
export function saveBlob(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
