import assert from 'node:assert/strict';import {caseState,emptyCase,validDate,addDays,daysBetween,elapsedDaysLabel,remainingDaysLabel,DEFAULT_RULES} from '../lib/domain.ts';
const r=DEFAULT_RULES;const base={...emptyCase(),client:'موكل',outcome:'لصالحنا',date:'2026-01-01',type:'حكم أول درجة'};
assert.equal(caseState(base,r,'2026-02-05').eligible,false);assert.equal(caseState(base,r,'2026-02-05').status,'بانتظار تأكيد الطعن');assert.equal(caseState({...base,appealConfirmation:'لا يوجد'},r,'2026-01-02').eligible,true);assert.equal(caseState({...base,appealConfirmation:'لا يوجد'},r,'2026-02-01').status,'جاهز للتنفيذ');assert.equal(caseState({...base,appealConfirmation:'تم'},r,'2026-02-01').eligible,false);assert.equal(caseState(base,r,'2026-01-31').remaining,0);assert.equal(caseState(base,r,'2026-01-26').alert,'خلال خمسة أيام');assert.equal(caseState(base,r,'2026-01-25').alert,'ضمن المهلة');assert.equal(caseState({...base,type:'حكم استئناف'}).due,'2026-03-02');assert.equal(caseState({...base,type:'إشكال'}).due,'2026-01-16');assert.equal(caseState({...base,role:'متهمة',outcome:'غير صالحنا',appealConfirmation:'لا يوجد'}).status,'جنح');assert.equal(caseState({...base,role:'متهم',outcome:'لصالحنا',appealConfirmation:'لا يوجد'}).eligible,true);assert.equal(caseState({...base,outcome:'غير صالحنا',appealConfirmation:'لا يوجد'},r,'2026-02-05').status,'بانتظار تأكيد الإجراءات');assert.equal(caseState({...base,outcome:'غير صالحنا',appealConfirmation:'لا يوجد',noActionConfirmation:'نعم'},r,'2026-02-05').status,'منتهي');assert.equal(validDate('2026-02-30'),false);assert.equal(addDays('2026-99-99',30),'');console.log('Passed: 30/60/15-day boundaries, execution eligibility, unknown confirmation, criminal exclusion, closure and invalid dates.');
const first=caseState({...base,date:'2026-09-01'},r,'2026-09-28');
assert.equal(first.elapsed,27);assert.equal(first.remaining,3);assert.equal(first.executionRemaining,3);
const appeal=caseState({...base,date:'2026-08-03',type:'حكم استئناف'},r,'2026-09-28');
assert.equal(appeal.elapsed,56);assert.equal(appeal.remaining,4);assert.equal(appeal.executionRemaining,-26);
assert.equal(caseState(base,r,'2026-01-31').remaining,0);
assert.equal(caseState(base,r,'2026-02-01').remaining,-1);
assert.equal(caseState(base,r,'2025-12-31').elapsed,-1);
assert.equal(daysBetween('2024-02-28','2024-03-01'),2);
assert.equal(daysBetween('2026-03-07','2026-03-09'),2);
assert.equal(daysBetween('2026-02-30','2026-03-01'),null);
assert.equal(caseState({...base,date:''},r,'2026-09-28').elapsed,null);
assert.equal(caseState({...base,type:'يحتاج مراجعة'},r,'2026-09-28').remaining,null);
assert.equal(caseState(base,r,'').remaining,null);
assert.equal(caseState(base,r,'').executionRemaining,null);
assert.equal(remainingDaysLabel(0),'اليوم');
assert.equal(remainingDaysLabel(-2),'انتهت منذ 2 يوم');
assert.equal(remainingDaysLabel(null),'غير محدد');
assert.equal(remainingDaysLabel(null,true),'نهائي');
assert.equal(elapsedDaysLabel(-1),'الحكم بعد 1 يوم');
assert.equal(elapsedDaysLabel(null),'غير محدد');
console.log('Passed: elapsed/remaining counters, selected report dates, execution timing, today, overdue, future, missing and invalid dates, leap years and DST boundaries.');
